# Mustaqbil Jobs
Jobs=[
    {
    'title':'Senior Graphic Designer',
    'companyName':'1 Key Solution',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'We are in search of Senior Graphic Designer to expand our team at our Islamabad office. You will be working under the supervision of the Creative Director and will work with other graphic designers, social media team and web team to deliver engaging designs to meet the clients’ needs and requirements.Our Office timings are 12:00 pm to 09:00 Pm.',
    'experience':'2 Years',
    'date':'14 August',
    'salary':'70,000 - 85000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/804125'
},
    {
    'title':'Content Writer - Resume Writing',
    'companyName':'Siggnitive Technologies',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'We are looking for the entry-level and experienced content writter for our team.Candidate can research and write industry-specific content for clients With English as their first language.candidate must be able to maintain relationships with clients, Including answering any questions they may have about the writing process or their resumes',
    'experience':'1 Year',
    'date':'12 December',
    'salary':'30,000 - 75,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/785315'
},
  {
    'title':'Sales / Business Development Executive / Officer - Fresh Graduates',
    'companyName':'Confidential',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'We are a corporate member of Pakistan Mercantile Exchange (PMEX) and offers top of the line trading facilities for market participants interested to trade in futures contracts offered by PMEX. We are now hiring BUSINESS DEVELOPMENT EXECUTIVES for our Karachi Office. Start a rearding career in sales, marketing and financial service, with an earning potential. I his role would suit a recent graduate or an entry level proressional, which is money-motivated and looking tor an opportunity to progress within a company.',
    'experience':'Fresh Graduate',
    'date':'20 December',
    'salary':'23,000 - 25,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/813114'
},
 {
    'title':'Pharmacist',
    'companyName':'Pillz Pharmacy',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'A wel-known pharmacy situated at islamabad, requires the services of an experienced, competent and self-motivated phar-macist immediately. As a pharmacist you will be responsible for preparing and administering appropriate rmaceuticals to patlents.',
    'experience':'4 Years',
    'date':'28 December',
    'salary':'40,000 - 48,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821386'
},

{
    'title':'Drivers & Loaders',
    'companyName':'Sparco Paints Region Office',
    'location':'Peshawar, Pakistan',
    'type':'Full-time',
    'Description':'Stock Delivery to concern dealer & rout. Reponsible for cleaning & vehicle mentaince',
    'experience':'2 Years',
    'date':'28 December',
    'salary':'18,000 - 25,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820442'
},
{
    'title':'Accountants',
    'companyName':'Saremco International',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'Saremco Intenational is an international trading company mainly exporting to east Asia and Middle east countries. vwe pro-duces and exports agricultural products. During the economic downturn, Saremco achieved remarkable growth, and would like to invite an accountants to boost Saremcos growth.',
    'experience':'5 Years',
    'date':'27 December',
    'salary':'50,000 - 100,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820156'
},
{
    'title':'IT Support Executive',
    'companyName':'Wurfel IT',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'Computer Skills, Knowledge of IT, Good Hands on MS office.Excel, Eager to Learn Tools, able to work at night',
    'experience':'Fresh Graduate',
    'date':'29 December',
    'salary':'20,000 - 40,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821805'
},
{
    'title':'Call Center Executive',
    'companyName':'TechieSquad',
    'location':'Islamabad, Pakistan',
    'type':'Part-time',
    'Description':'Techiesquad is currently looking for energetic and passionate International Call Center Executives to join our team, we are hiring experienced and fresh candidates (Both male and females) for our DME Campaign.',
    'experience':'1 Year',
    'date':'29 December',
    'salary':'18,000 - 35,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821575'
},
{
    'title':'Webmaster',
    'companyName':'Baqai Medical University',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'we are loOking for a webmaster to maintain websiteS and servers to meet user needs. He/ she will be responsible to, Build functional and easy-to-use websites, Test websites across browsers, operating systems, and devices, Ensure site security by setting up firewalls and login pages, Optimize loading speeds and capacity, Debug pages and fix broken links or images, Update website content and review SEO, Monitor and analyse site performance (e.g. traffic, conversions)',
    'experience':'2 Year',
    'date':'29 December',
    'salary':'40,000 - 50,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821578'
},
{
    'title':'SEO Internship',
    'companyName':'Raresoft',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':"This is office based. Must have at least 3 years of experience in digital marketing. The candidate must have at least a university degree.Candidate will be responsible for managing all her SEO activities such as content strategy, link building and keyword strategy to improve rankings on all major search networks. We need experts in web content writing and social media blogging, content writing, Facebook marketing. Twitter marketing, Google Adsense for website building. The company had to meet the client's requirements based on their experience in ranking websites web pages on variour search engines using white hat SEO techniques. Create a backlink strategy that drives traffic to your website with quality white hat backlinks.",
    'experience':'1 Year',
    'date':'28 December',
    'salary':'1,000 - 5,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821130'
},
{
    'title':'Call Center Executives (US English Speaking Accent)',
    'companyName':'Farwah Tech',
    'location':'Multan, Pakistan',
    'type':'Full-time',
    'Description':'Hey there, we are looking Tor call center agents that nave experience working as customer service representatives ana/or are willing to learn. The most important qualification we are looking Tor is: Excellent English pronunciation and communication skills. Candidates with previous experience will have an edge when applying. However, new agents with excellent pronunciation Skills, but so much customer service experience, can also apply as long as they have a good attitude and are willing to learn.',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'40,000 - 45,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/767946'
},
{
    'title':'Link Builder',
    'companyName':'SERP Klicks',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'Researching potential websites and people for outreach, Conducting a content audit to identity linkable potentials, Performing keyword research and identifying the best keywords for SEO-optimized content projects, Monitoring and promoting blog posts and other content to be used for backlink purposes, Working With copywriters and web developers in continuous monitoring and improvement of content and website architecture for better SERP ranking, Consistent monitoring and assurance of the clients websites healthy backlink profile',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'10,000 - 20,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820438'
},
{
    'title':'Lead Generator',
    'companyName':'Rainbow Communications Pvt Ltd.',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'We are looking tor someone who is full of energy, target driven, focused, wants to earn bonus and grow in their career.',
    'experience':'1 Year',
    'date':'6 December',
    'salary':'45,000 - 80,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/795834'
},
{
    'title':'Sales Representative',
    'companyName':'United Solar',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'United Solar Investment Development PIY LID was established in sydney, Australia to facilitates the development and financing of photovoltaic solar projects through its online platform, promotes photovoltaic solar energy and technology as the key to a sustainable future, and helps countries strengthen photovoltaic solar maximum capacity',
    'experience':'1 Year',
    'date':'30 November',
    'salary':'500,000 - 200,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/789179'
},
{
    'title':'PHP Developer',
    'companyName':'Clixosoft',
    'location':'Lahore, Pakistan',
    'type':'Part-time',
    'Description':'We are looking for experienced PHP / Word Press -Developers. As a Web Developer your skills should include: PHP HTML5, JavaScript / Jquery. CSS3, Bootstrap and any PHP Frame Work. Experience of WordPress to build websites both from scratch and to add functionality in existing WordPress sites. Have the ability to work independently and with deadlines.',
    'experience':'2 Year',
    'date':'29 December',
    'salary':'25,000 - 60,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821860'
},
{
    'title':'Web Computer Administrator & Virtual Assistant',
    'companyName':'Mazz Developments Ltd',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'Seeking an experienced individual to create web / hosting presence. Support building a resilliant web Sites. Help with internet search, social media and perform administrative tasks on a daily bases. The individual must have excellent technical skills, be a self starter Knowledge and experience of gsuite as well as excel/google sheets is a must. You will be required to administer account entries using google sheets.',
    'experience':'2 Year',
    'date':'28 December',
    'salary':'15,000 - 30,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821159'
},
{
    'title':'IT Executive',
    'companyName':'Max Inc',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'Miracle Solutions LLC Is looking for Post Graduates with a good GPA and strong knOwledge of WindowS and MacOS.',
    'experience':'2 Year',
    'date':'28 December',
    'salary':'40,000 - 45,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820441'
},
{
    'title':'Sales Manager',
    'companyName':'PostEx Services (Private) Limited',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'The ideal candidate will be responsible for business development and should be skilled at building and maintaining relationships with clients and work to provide exceptional customer service to clients.',
    'experience':'3 Year',
    'date':'29 December',
    'salary':'100,000 - 200,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821857'
},
{
    'title':'Assistant Manager Sales - Real Estate',
    'companyName':'Malqiyet',
    'location':'Faisalabad, Pakistan',
    'type':'Full-time',
    'Description':'We are seeking a highly motivated and organized Assistant Manager of Sales to join our team at [Company Name]. Ihe assistant manager of Sales will be responsible for managing a team of sales agents and driving property sales within our company.',
    'experience':'3 Year',
    'date':'29 December',
    'salary':'10,000 - 35,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821579'
},
{
    'title':'Manager Sales',
    'companyName':'Best Power Services',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'Conducts sales calls, schedules promotional activities and tracks sales for a selected portfolio of accounts.',
    'experience':'1  Year',
    'date':'29 December',
    'salary':'50,000 - 80,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821197'
},
{
    'title':'Fresh Graduates',
    'companyName':'Splash Tech',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'Its an office-based Lahore job, not a remote job. Splash tech company hiring a fresh content writer, Full-time job for experienced, Internship for Freshers. Duties: Assist Content writers, Do the work content writer assign.(If you are totally fresh in content writing we will provide you training). Requirements: Good written and verbal english communication skills, Interested in games and movies, Good Command on Grammar and Vocabulary, Multi-tasker.',
    'experience':'Fresh Graduate',
    'date':'29 December',
    'salary':'20,000 - 30,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821576'
},
{
    'title':'Duty Medical Doctor',
    'companyName':'Mars Associates',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'Medical care, Patient care, Process and Quality, Staff and Facility Management ',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'35,000 - 50,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821086'
},
{
    'title':'Graphic Designer',
    'companyName':'S2S Marketing',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'We are hiring graphic designer for our Islamabad office',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'45,000 - 55,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820443'
},
{
    'title':'Customer Sales Representative',
    'companyName':'Aspire',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'Aspire telecom is looking tor individuals, wiling to challenge themselves and grow their skills in the telemarketing and sales. We are looking for fresh and experienced individuals with great verbal communication skills, for international projects/campaigns .Keeping customer satisfaction at the core of every decision and behavior.',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'20,000 - 45,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820195'
},
{
    'title':'Software Engineer - Asp .Net',
    'companyName':'Live Technologies',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'Livetecs LLC is looking for a mid-level software engineer who must have 2 to 3 years or experience and a genuine passion for developing disruptive software solutions. This is an amazing opportunity to take the next step in your career by working on the latest technologies and patterns.',
    'experience':'2 Year',
    'date':'6 December',
    'salary':'70,000 - 100,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/795831'
},
{
    'title':'Marketing Executive',
    'companyName':'Students Solution Uk Limited',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'Welcome Walk In Inquiries, Career Counselling, University Information, Follow-up Inquiries, Closing Admissions, Facilitating Complains and Feedback, New ideas.',
    'experience':'1 Year',
    'date':'29 December',
    'salary':'30,000 - 45,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821858'
},
{
    'title':'Global DLP Analyst',
    'companyName':'FINCA Impact Finance',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'A CAREER ADVANCING FINANCIAL INCLUSION: ABOUT FINCA IMPACT FINANCE:  FINCA Impact Finance (FIF) believes in the power of inclusive Finance. FINCA Impact Finance is a global leader of responsible financial services. We are comprised of 19 full-service banks and mi-crofinance institutions and a holding/shared service company and we serve more than 2.8 million customers with an array fintech and traditional products and services. We are a double bottom line company that delivers positive social impact and financial sustainability.',
    'experience':'3 Year',
    'date':'29 December',
    'salary':'100,000 - 100,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821853'
},
{
    'title':'Graphic Designer & Camera Operator',
    'companyName':'Invest Habico Pvt. Ltd.',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'Hi everyone we need a experienced graphic designer for a Real state Company, Who can also handle professional camera and drone camera perfectly. Candidate must have proper grip on Adobe Photoshop and should know how to operate professional Camera + Drone Camera which will be provided by the company so that he can cover events and meetings. And should have the ability to design media campaigns for media marketing. And one last important thing after showing his working skills and efforts salary will increased for sure. So candidates should not focus on offering package its totally de-pending on your work that how early you are going to prove yourself. Only serious persons should contact.',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'25,000 - 30,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821119'
},
{
    'title':'Sales Executive',
    'companyName':'Backhaul Dispatchers Private Limited',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'You will be responsible for driving the sales process with potential prospects. Contact Prospective clients through cold calls and emails, Achieve all individuals activity and revenue targets set by the company, Provide recommendations based on the prospects business needs and negotiate contract terms, Set up meetings/calls between prospective clients and account executives, Work across multiple departments to ensure common objectives are reached, Reschedule/Follow up with prospects if meetings donot occur.',
    'experience':'1 Year',
    'date':'27 December',
    'salary':'35,000 - 45,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820173'
},
{
    'title':'Sr. Android Developer',
    'companyName':'SmartObject',
    'location':'Islamabad, Pakistan',
    'type':'Full-time',
    'Description':'Sr. Android Developer will be responsible for: Developing, design and build new generation mobile applications for multiple versions of android devices. Contribute in building exquisite applications by working in close coordination with the android developers team and Graphics Designer, Monitoring apps technical li-cycle during development phase, Update and maintain design specifications and source code for new apps, Evaluate existing applications and maximize apps effeciency by fixing bugs and implement new technologies, Ensuring smooth team operations and effective collaboration being contact point for team members.',
    'experience':'3 Year',
    'date':'29 December',
    'salary':'35,000 - 75,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/821574'
},
{
    'title':'SEO Content Writer / Copywriter',
    'companyName':'HA Marketer',
    'location':'Pakistan',
    'type':'Full-time',
    'Description':'Work on assigned topics/ articles, search for new topics, plan, write and edit articles ,blogs. details will be provided by us. For this Job, You will have to work minimum 8 hours a day. And you should be able to complete the work in given amount of time. You will need to give Minimum 20 Articles daily. There are no days off tor this work, if you want to take a day oft payment will be deducted for that day. It requires your 100% dedication and commitment to work. Fresh graduates with some project-based experience may also apply. Students will be considered for internships only.',
    'experience':'1 Year',
    'date':'8 December',
    'salary':'22,000 - 30,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820444'
},
{
    'title':'Dispatcher',
    'companyName':'Groundlink Worldwide',
    'location':'Lahore, Pakistan',
    'type':'Full-time',
    'Description':'The required candidate is respoinsible for follw ups of rides With drivers and contacting the customers to let them know that driver is on location. The candidate will be responsible for making reservations according to customer requirements.',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'30,000 - 50,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820439'
},
{
    'title':'Education Consultant',
    'companyName':'FNK Associates',
    'location':'Karachi, Pakistan',
    'type':'Full-time',
    'Description':'We are seeking an Education Consultant who will have primary responsibility for advising students about UK study options and other student pathways. The individual will be managing online and phone inquiries as well as being responsible for business development work tor the company -1e. helping to drive sales by cold calling prospective education institutions, students. The role will require building relationships with prospective clients/students as well as maintaining existing clients/students. The role will also involve marketing with a strong emphasis on digital marketing content development (e. Facebook and other forms of social media). The ideal candidate will have experience in all stages of the sales and marketing cycle. The role will have responsibility for managing the sales pipeline, analyzing market trends and advising management doubt these.',
    'experience':'1 Year',
    'date':'28 December',
    'salary':'20,000 - 25,000 PKR',
    'link':'https://www.mustakbil.com/jobs/job/820188'
},
]
